### ISSUE TITLE
Touch id screen localization 

### ISSUE THREAD

**Issue by gish94** [fnzc/react-native-pincode#24]
Is there any way to change localization for touch id screen texts? 
![device-2018-08-15-122154](https://user-images.githubusercontent.com/8583056/44138726-ecaf3028-a085-11e8-82c2-4fdabfec78d3.png)

**Comment by Haskkor** [comment]
Hi :)

Sorry for the delay. 
It seems like something to add i18n in react-native-touch-id is on its way. 
https://github.com/naoufal/react-native-touch-id/pull/99
You can maybe check if it will be fixed soon and I’ll update the version. 

Cheers

**Comment by Haskkor** [comment]
Hi,

It seems fixed in the latest version of react-native-touch-id. The PR supposing to fix it was merged anyway.
I updated the version in v1.7.1. Tell me if it works for you now please.

Cheers,
Jeremy
