### ISSUE TITLE
Delete button stylePinCodeDeleteButtonColorHideUnderlay property

### ISSUE THREAD

**Issue by justincrow** [fnzc/react-native-pincode#25]
This property is not applied until the Delete button is pressed once.

The problem appears to be in PinCode.js, line 223, where the state is set to the default `colorDelete: 'rgb(211, 213, 218)'` instead of checking if the property `styleDeleteButtonColorHideUnderlay` has been supplied, as it does for example in `onHideUnderlay`.

**Comment by Haskkor** [comment]
Thanks a lot for letting me know. I'll fix this this evening or tomorrow and let you know when it's done.

**Comment by justincrow** [comment]
That's great, thanks very much.

We love the package you've written - it's the best out there.

Justin

**Comment by Haskkor** [comment]
Fixed in v1.6.2 :)

**Comment by justincrow** [comment]
Excellent, thank you.
