### ISSUE TITLE
PIN validation

### ISSUE THREAD

**Issue by justincrow** [fnzc/react-native-pincode#32]
Hi,

I wondered if you'd thought of adding pluggable validation rules when choosing a PIN, such as non-sequential numbers, and non-repeating numbers.

Or perhaps just a couple of new parameters that allow restricting the use of sequential numbers and all repeating numbers?

If not, would you accept a pull request?

Thanks.

**Comment by Haskkor** [comment]
Hi,

This is a really cool idea :). I'll give it a thought during the weekend. 
Thanks!

Cheers
Jeremy

**Comment by timt** [comment]
Hi,

Great idea. Are you likely to add this feature soon? Would you like a pull request for it?

--Tim

**Comment by Haskkor** [comment]
Hi, 

Sorry for the delay @timt . 
I started to work on this today. Will keep in touch.

Cheers,
Jeremy

**Comment by Haskkor** [comment]
Hi,

This is done in version 1.7.0 :).
I chose to go for the RegExp solution. 
You can now use `validationRegex` property to check the PIN entered by the user and the `titleValidationFailed` one to tweak the title displayed if the check fails.

Thanks again for this idea :).

Cheers,
Jeremy
