### ISSUE TITLE
how to use guide example ?

### ISSUE THREAD

**Issue by klingofmonsterdev** [fnzc/react-native-pincode#33]
status: choose or enter has a function related ?
Want to make an example of how to use status: choose or enter?

**Comment by Haskkor** [comment]
Hi,

I'll make a full example project as soon as possible.
In the mean time, I don't really know what to tell you.

Basic usage is: 
```
import PINCode from '@haskkor/react-native-pincode'
<PINCode status={'choose'}/>
```

or:
```
import PINCode from '@haskkor/react-native-pincode'
<PINCode status={'enter'}/>
```

to see the 2 different modes.
If you want to know how to switch between the 2 different statuses, you could use 2 different pages as we do or store a global status depending on you app flow in a state somewhere I suppose :).

Cheers,
Jeremy

**Comment by cshung1994** [comment]
Hi,
How to use bottomLeftComponent?

**Comment by Haskkor** [comment]
Hi,

Here is an example.

```
class App extends React.PureComponent<IProps, IState> {

  render() {
    return (
      <View style={styles.container}>
        <PINCode status={'choose'} stylePinCodeEmptyColumn={styles.bottomLeft} 
           bottomLeftComponent={
             <View style={{backgroundColor: 'red'}}><Text style={{color: 'yellow'}}>test</Text></View>
           }/>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF'
  },
  bottomLeft: {
    marginLeft: grid.unit / 2,
    marginRight: grid.unit / 2,
    alignItems: 'center',
    width: grid.unit * 4,
    height: grid.unit * 4
  }
})
```

`stylePinCodeEmptyColumn` => this is the style of the view
`bottomLeftComponent` => this is the component

This is the result:

![screen shot 2018-12-10 at 3 10 41 pm](https://user-images.githubusercontent.com/10620919/49706957-da6d8900-fc8d-11e8-93b0-d492f6434bc0.png)


Cheers,
Jeremy

**Comment by cshung1994** [comment]
Thank you for your reply, I follow your steps and even copy the source code directly, but my screen will still not display the button, is there a problem?
<img width="271" alt="2018-12-13 2 16 41" src="https://user-images.githubusercontent.com/33892812/49919616-231d8000-fee2-11e8-82bc-9d33ad6a3525.png">

I set grid.unit  =  16

**Comment by Lepozepo** [comment]
@cshung1994 sadly the `bottomLeftComponent` property doesn't check for functions. You might be passing a function instead of a component.

This fails:
```
        bottomLeftComponent={() => (
          <View style={{backgroundColor: 'red'}}><Text style={{color: 'yellow'}}>test</Text></View>
        )}
```

This works:
```
        bottomLeftComponent={
          <View style={{backgroundColor: 'red'}}><Text style={{color: 'yellow'}}>test</Text></View>
        }
```

**Comment by Xeizzeth** [comment]
> This works:
> 
> ```
>         bottomLeftComponent={
>           <View style={{backgroundColor: 'red'}}><Text style={{color: 'yellow'}}>test</Text></View>
>         }
> ```

Actually no, this doesn't. It gives "not a function" error.
