### ISSUE TITLE
How to use custom passwordcomponent 

### ISSUE THREAD

**Issue by Codedrainer** [fnzc/react-native-pincode#34]
This is  my code , please help me

`
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import Pincode from './react-native-pincode';
import Password from './src/pincode/index';

type Props = {};
export default class App extends Component<Props> {
    renderPassword(){
        return(
            <Password/>
        )
    }
  render() {
    return (
           <Pincode
               status={'choose'}
               passwordComponent={this.renderPassword()}
               passwordLength={4}
           />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },

});
`

**Comment by Haskkor** [comment]
Hi,

I'll try your code and give you an example soon. :)

Cheers,
Jeremy

**Comment by Haskkor** [comment]
Hi,

I'm sorry I don't have much time those days to work on this. 
I tried it and it's broken. I'll fix it as soon as possible.

Cheers,
Jeremy
