### ISSUE TITLE
[Bug] java.lang.SecurityException: Requires VIBRATE permission

### ISSUE THREAD

**Issue by Peretz30** [fnzc/react-native-pincode#35]
### How to reproduce
Use android
### How to fix
Add
`<uses-permission android:name="android.permission.VIBRATE"/>`
to 
> AndroidManifest.xml

**Comment by Haskkor** [comment]
Hi,

Thanks for that :).
I'll add a note in the readme to let people know that they have to add the permission.

Cheers,
Jeremy
