### ISSUE TITLE
Show PIN code

### ISSUE THREAD

**Issue by justincrow** [fnzc/react-native-pincode#37]
Hi,
Another suggestion we have is to have a configuration option to show the PIN code as the user types. This would be useful when entering an MFA code, as opposed to a PIN.
Best regards,
Justin

**Comment by Haskkor** [comment]
Hi,

Another good idea :).
I started to work on it. Need to change styling a bit, shouldn't take long.

Cheers,
Jeremy

**Comment by Haskkor** [comment]
Hi,

I added the `pinCodeVisible` property (along with `textPasswordVisibleFamily` and `textPasswordVisibleSize`) in version 1.6.6.
Style could still be improved but it's usable :)

Cheers,
Jeremy

**Comment by justincrow** [comment]
Great - many thanks Jeremy :)
