### ISSUE TITLE
Clear Pin Code after account was locked

### ISSUE THREAD

**Issue by marla-singer** [fnzc/react-native-pincode#38]
### Steps for reproduce

1. Try to login and enter PIN Code incorrectly some times so access is locked
2. Wait until the time is over and Enter your PIN Code step is shown again
3. See pict.  Note that the 4 PIN Code dots are filled/completed.  The user has to manually deleted them before entering the 4 digits again

![image](https://user-images.githubusercontent.com/20643403/46001677-8d2d4280-c0b4-11e8-808c-aca47e46b9a8.png)

4. It would be nice to show the 4 dots cleared as when first requested

![image](https://user-images.githubusercontent.com/20643403/46001694-9b7b5e80-c0b4-11e8-9ad3-d7caf0ad736f.png)

### Solution

I've made the dirty hack to fix it and I'm using that
https://github.com/marla-singer/react-native-pincode/blob/2a39d1bff9d560c9d860b1aa05fc9458ec063fb3/src/PinCode.tsx#L137

If it's okay for you then I can prepare PR. If it isn't then I'm looking forward to see your changes and a new version of the library :)

**Comment by Haskkor** [comment]
Hi,

Solution is perfectly fine by me :). I had a bit of time this morning so I integrated your solution and published a new version.

Thanks a lot for that :)

Cheers
Jeremy

**Comment by marla-singer** [comment]
Thanks a lot!

**Comment by mehedi123hessan-bit** [comment]
-###
