### ISSUE TITLE
Can set pinStatus to failure only once inside handleResultEnterPin

### ISSUE THREAD

**Issue by tkulpa** [fnzc/react-native-pincode#48]
```
import PINCode, { PinResultStatus } from '@haskkor/react-native-pincode'

<PINCode
 status={'enter'}
 pinStatus={this.state.pinStatus}
 handleResultEnterPin={this.handleResultEnterPin}
 onFail={this.onFail}
/>
```
I have simple pin code component then, inside handleResultEnterPin Im setting pin status to failure
        `this.setState({ pinStatus: PinResultStatus.failure })`

And after first entry I can retype pin, but then component just stuck on second entry last digit and onFail is not being fired

Expected behaviour: I should be able to retype pin code as many times as I want and handle this inside onFail method that is being fired after state being changed to failure

**Comment by Haskkor** [comment]
Hi,

Sorry for the delay. I'll investigate during the week.

Cheers,
Jeremy

**Comment by Haskkor** [comment]
I've made a quick fix.
It's not stuck after 2 tries now. However the locked screen is still triggered after X attempts.

Tell me if that's ok or if you need more :)

Cheers,
Jeremy
