### ISSUE TITLE
Feature request: custom left bottom button component

### ISSUE THREAD

**Issue by jur4j** [fnzc/react-native-pincode#49]
Hi. First of all thanks for library, I like many possibilities for customization. But now I am missing one.

Could you please add property where I can define custom component, which will be rendered in the left bottom corner of numpad (now there is nothing rendered) ?
So it would be something like
`buttonLeftBottomComponent={() => <MyCustomButton title={...} onPress={...} />}`.
I could really use that button for some actions.

**Comment by Haskkor** [comment]
Hi :),

I'll add that during the week. 

Cheers,
Jeremy

**Comment by Haskkor** [comment]
Hi, 

I've added a `bottomLeftComponent` prop in 1.9.0.

Cheers,
Jeremy
