### ISSUE TITLE
Remove pin option? 

### ISSUE THREAD

**Issue by ssilverr** [fnzc/react-native-pincode#50]
Hi!

I was wondering what can you do, once you set the pin code and want to remove it later. I used Keychain.resetGenericPassword, but the hasUserSetPinCode still returned with true, even though the pin code i set no longer worked :/ 

Would it be possible to one more option to pinSatus ('reset') ?
I will try yo look into it in the meantime

**Comment by Haskkor** [comment]
Hi,

I've just added a function in v1.8.0 to delete the PIN code :).

```
import {deleteUserPinCode} from '@haskkor/react-native-pincode'
deleteUserPinCode()
```

Thanks for the idea 👍 

Cheers,
Jeremy

**Comment by ssilverr** [comment]
Sweet! Thanks for the quick work! 👍
