### ISSUE TITLE
Feature request: show / hidden password circle background

### ISSUE THREAD

**Issue by Rezaramdhanisti** [fnzc/react-native-pincode#52]
Hello, can i customize the background when show and hidden? 

Thanks

**Comment by Rezaramdhanisti** [comment]
Thank you Jeremy but i cant customize like black when clicked and white when not

**Comment by Haskkor** [comment]
Hi,

You can by using the `stylePinCodeButtonCircle` property to provide the 'no-clicked' button color.

```
      <View style={styles.container}>
        <PINCode status={'choose'} numbersButtonOverlayColor={'black'} stylePinCodeButtonCircle={{
          alignItems: 'center',
          justifyContent: 'center',
          width: 64,
          height: 64,
          backgroundColor: 'blue',
          borderRadius: 32
        }}/>
      </View>
```

Cheers,
Jeremy

**Comment by Rezaramdhanisti** [comment]
Thank you so much but i mean this one, 
![image](https://user-images.githubusercontent.com/16949529/49197881-4533e000-f3c3-11e8-860f-04cbaf88a7b6.png)

really appreciate your answer!

**Comment by Haskkor** [comment]
Hi,

So sorry for the misunderstanding...
Just to be sure this time, do you want to change the background (deep blue) or the dots (light blue)?
If it's the dots you're talking about, you want to have a different color when they are small and big?

Cheers,
Jeremy

**Comment by Rezaramdhanisti** [comment]
Hi,
Thank you for your response yes i mean when the dots are fullfilled and when not.
Can i customize when fullfilled black and when not white ?

Thanks

**Comment by Haskkor** [comment]
Hi,

I've just added `colorPasswordEmpty` property.
You can now use `colorPassword`, `colorPasswordEmpty`, and `colorPasswordError` :)

Cheers,
Jeremy

**Comment by Rezaramdhanisti** [comment]
Hiiii,
Thank you so much for the feedback i just upgraded the version and its working on Android but on iOS **colorPasswordEmpty** not working
