### ISSUE TITLE
Request service for hasUserSetPinCode and deleteUserPinCode

### ISSUE THREAD

**Issue by dungnguyen10989** [fnzc/react-native-pincode#55]
I using PINcode to secure my token, but in my app, I also using keychain to storage some other values by storage with other service. But if I save any item to keychain, and then call the method hasUserSetPinCode, it always return true, whether PINCode I have not set anywhere. Please provide a params for hasUserSetPinCode() like service to get value that they are not in my service.

**Comment by Haskkor** [comment]
Hi,

The function I'm using to store the pincode in the keychain doesn't allow me to provide a service name. I'll use a new one and come back to you.
Thanks for pointing this out.

Cheers,
Jeremy

**Comment by Haskkor** [comment]
Hi,

It's fixed now. You can use the `pinCodeKeychainName` property to provide a service name. 

Cheers,
Jeremy
