### ISSUE TITLE
handleResultEnterPin changed to handleResult

### ISSUE THREAD

**Issue by tkulpa** [fnzc/react-native-pincode#56]
Nothing in docs, and getting ts error while trying to pass handleResult (incorrect types I guess)

**Comment by Haskkor** [comment]
Hi,

I don't know what you're talking about tbh. :)

This is the index.tsx:

https://github.com/fnzc/react-native-pincode/blob/5001c5b36b99ac71897a951cb822df7376938087/index.tsx#L21

The index.d.ts:

https://github.com/fnzc/react-native-pincode/blob/5001c5b36b99ac71897a951cb822df7376938087/dist/index.d.ts#L16

And the index.js:

https://github.com/fnzc/react-native-pincode/blob/5001c5b36b99ac71897a951cb822df7376938087/dist/index.js#L51

I just tried it and I can't use `handleResult`, just `handleResultEnterPin`.

Cheers,
Jeremy

**Comment by tkulpa** [comment]
https://github.com/fnzc/react-native-pincode/blob/master/src/PinCodeEnter.tsx#L127

**Comment by Haskkor** [comment]
But what would you use this directly?
The name is changed inside the component for convenience but if you invoque the PINCode as stated in the doc through the status property it’s working as it should. 

Cheers,
Jeremy

**Comment by tkulpa** [comment]
@Haskkor Hey Jeremy, I mean after update Im having issue with handling pin on my own, Im getting this error, and still didnt track sources for that, I checked code and thought that this could be reason
https://github.com/fnzc/react-native-pincode/blob/master/src/PinCodeEnter.tsx#L135
But shouldnt get there in first place as Im providing my own handler
https://github.com/fnzc/react-native-pincode/blob/master/src/PinCodeEnter.tsx#L126
![image](https://user-images.githubusercontent.com/18174866/49430221-bc45eb80-f7aa-11e8-8f13-c4b5c6bea0a6.png)

**Comment by Haskkor** [comment]
Hi

**Comment by tkulpa** [comment]
@Haskkor Im not using storedPin as Im not storing pin, Im encrypting data and then trying to decrypt it with pin user inputted, if it fails I know that pin was incorrect otherwise all good. So I dont need to store pin at all

**Comment by Haskkor** [comment]
Hi,

Sorry for the misunderstanding :).
I tried to fix this without breaking the other things I've fixed/added lately.
Please test version 1.10.6 and tell me :).

Cheers,
Jeremy

**Comment by tkulpa** [comment]
Hey, great job! Everything is working as expected
