### ISSUE TITLE
Deprecated React Lifecycle Methods

### ISSUE THREAD

**Issue by justincrow** [fnzc/react-native-pincode#58]
Hi,

Do you plan to migrate away from the deprecated React methods such as:
componentWillReceiveProps
componentWillUpdate

Thanks,
Justin

**Comment by Haskkor** [comment]
Hi,

I forgot about this so yes, I'll do it soon :).
Thanks for reminding me!

Cheers,
Jeremy

**Comment by justincrow** [comment]
Great stuff - thanks!

**Comment by Haskkor** [comment]
Hi,

Done in 1.10.7 :)

Cheers,
Jeremy

**Comment by justincrow** [comment]
Awesome - responsive as always! :)
