### ISSUE TITLE
pinStatus property no longer being used!

### ISSUE THREAD

**Issue by timt** [fnzc/react-native-pincode#59]
Hi,

The fix for #48 in commit e26fb9d219aab3d29a05a64925b4a0e5460b46a1 now means that when we set pinStatus on PINCode this value is now overwritten in the method endProcess. We need a way to be able to replace the method endProcess(pinCode) with our own handler completly. Just to be clear we are not using the storedPin approach, and instead manage the pinStatus property ourselves.

**Comment by Haskkor** [comment]
Hi,

I've added a `endProcessFunction` property to replace the endProcess function complete :).

Cheers,
Jeremy

**Comment by timt** [comment]
Perfect thanks :)
