### ISSUE TITLE
How can I use bottomLeftComponent?

### ISSUE THREAD

**Issue by cshung1994** [fnzc/react-native-pincode#61]
How can I use bottomLeftComponent ?
I set this value to any but it seems not work

**Comment by Haskkor** [comment]
Hi,

`any` is a type, it's not a value that you can set: https://www.typescriptlang.org/docs/handbook/basic-types.html

Here is an example: https://github.com/fnzc/react-native-pincode/issues/33#issuecomment-445627825 

Cheers :),
Jeremy
