### ISSUE TITLE
TouchId Custom ? (Title,Message)

### ISSUE THREAD

**Issue by Toshihiro2010** [fnzc/react-native-pincode#65]
i want chang title and message for TouchID.

Thank you.

**Comment by Haskkor** [comment]
Hi,

The `touchIDSentence` property is available to change the message. 
I've added a `touchIDTitle` property in v1.13.0 for the title but please note that it's only working on Android (https://github.com/naoufal/react-native-touch-id#authenticatereason-config).

Cheers,
Jeremy

**Comment by ajulien42** [comment]
Just proposing, may be you should just pass a full object as "touchIdProps" that match react-native-touch-id optionnalConfig Object: {
title: 'Authentication Required', // Android
  imageColor: '#e00606', // Android
  imageErrorColor: '#ff0000', // Android
  sensorDescription: 'Touch sensor', // Android
  sensorErrorDescription: 'Failed', // Android
  cancelText: 'Cancel', // Android
  fallbackLabel: 'Show Passcode', // iOS (if empty, then label is hidden)
  unifiedErrors: false, // use unified error messages (default false)
  passcodeFallback: false, // iOS
};
Your component is great but it already has a lot of props, and maybe tomorrow someone will ask to change the touchIdIconColor etc...

**Comment by Haskkor** [comment]
Hi @ajulien42 

You're right. I'll change it next time I have to add a prop :D

Cheers,
Jeremy
