### ISSUE TITLE
How to catch error after cancel touch id?

### ISSUE THREAD

**Issue by Gaever** [fnzc/react-native-pincode#67]
Hi!
As soon as user cancel fingerprint/faceid dialog an uncaught error is thrown. Is there way to handle it? I'm trying to implement bottomLeft component with biometry icon so user could perform new attempt to authorize with biometry. 
I'd be glad to pass callback to your component's prop that fires when error is thrown.

**Comment by Haskkor** [comment]
Hi,

It's a good idea but I don't think we'll have time to work on this soon. I'll leave this open but you're welcome forking/making a pull request for this if you need it sooner :)

Cheers,
Jeremy

**Comment by Gaever** [comment]
Hi Jeremy,

Thanks for reply. Ok, got you. It’s not big deal for now, I just hide yellowbox. But I like your component and would like to PR this feature in about 2 weeks.

**Comment by Haskkor** [comment]
Hi,

I've added a property called `callbackErrorTouchId?: (error: Error) => void` that is triggered when the TouchID function throws an error. 

Cheers,
Jeremy
