### ISSUE TITLE
Changing the color of the button circle

### ISSUE THREAD

**Issue by zaharidichev** [fnzc/react-native-pincode#69]
Hi there, currently one can overwrite the whole style of the circle button via the `stylePinCodeButtonCircle`. This is great. However we are only looking to change the color. The style defines the radius of the circle which by the looks of it is based on react native grid. Instead of overwriting the whole style and dealing with setting the appropriate radius, etc, is there any current way to only overwrite the color of the button (in non selected state)

**Comment by Haskkor** [comment]
Hi!

The radius is not defined by RN grid. The `grid.unit` comes from a constants file that I made (grid.ts). A unit is defined as 16px in this file.
Anyway, I've added a `colorCircleButtons` property in latest version so you can just change the color with this 😄 .

Cheers,
Jeremy
