### ISSUE TITLE
"Number of attempts" and "last time of attempt" not reset when deleting user PinCode

### ISSUE THREAD

**Issue by shuchenliu** [fnzc/react-native-pincode#70]
Part of our app logic is like this:  

0. During logging in process, we asked the user to set a pin by using `<PinCode status={'choose'}`
1. Some time later, when app state changes, we render `<PinCode status={'enter'}` to prompt the user to enter the said pin.
2. If `maxAttempts` reached, we delete the user pin and logged the user out, navigating back to Login screen.  
3. User can choose from there to log back in and set the pin again.

However, when we render again `<PinCode status={'choose'}` in **step 3**, we encountered a timed locked out screen.   
It seems that `<PinCode status={'choose'}` does not take the `disableLockScreen` props and after further investigation, we found that the internal states including `last time of attempt` and `number of attempts` were not properly reset after user pin code deletion, which triggered the `<PinCode status={'choose'}` to render the locked out screen.

Would it make sense, that when we delete user pin code, we would also want to reset internal states associated with that pin code, such as `pinAttempts` and `timePinLocked`?

I'll submit a sample pull request later, please feel free to modify it or reject it if it does not really fit in. I'd work more on this if you think this needs to be addressed.

**Comment by Haskkor** [comment]
Hi,

Thanks a lot for that! It's merged and available in latest version. 

Cheers,
Jeremy
