### ISSUE TITLE
RNKeychainManager.setInternetCredent ialsForServer got 6 arguments, expected 7

### ISSUE THREAD

**Issue by Sarvarr** [fnzc/react-native-pincode#73]
![Screenshot_2019-03-15-23-14](https://user-images.githubusercontent.com/35866742/54472490-051a3100-47eb-11e9-97da-c2080f3398ae.jpg)

**Comment by teanz** [comment]
Having the exact same issue.

I think it maybe an issue with react-native-keychain as I've tried to set the pin code using the RNKC package directly and still recieve the same error.

I can't seem to find what I'm missing....

Help would be appreciated.

**Comment by teanz** [comment]
Ok so I had v 3.1.1 of react-native-keychain which seems to break setting a pin code. If you roll back to v3.0.0 of react-native-keychain it fixes the issue.

**Comment by Haskkor** [comment]
Thanks @teanz. Is it helpful for you as well @Sarvarr ?

**Comment by Sarvarr** [comment]
Thanks @tean 👍

**Comment by marcelcure** [comment]
Please see my comment https://github.com/jarden-digital/react-native-pincode/issues/136#issuecomment-646207063
