### ISSUE TITLE
Customize HiddenPasswordCircle (small dots over numbers)

### ISSUE THREAD

**Issue by IntegralTeam** [fnzc/react-native-pincode#74]
Is it possible to customize these dots? There is a colorPassword prop for changing color of dots, but I also need to add borderColor and borderWidth to them.

**Comment by Haskkor** [comment]
Hi,

Is the `passwordComponent` prop what you're looking for? 

Cheers,
Jeremy

**Comment by IntegralTeam** [comment]
Hello! Thank you for quick response.

Yes, as I get it `passwordComponent ` is used to completely replace default dots component. But what I want is to give default component my own styles.

I see I can use `stylePinCodeHiddenPasswordCircle` but it seems that it styles wrapper for these dots instead of styling each dot separate. Adding borderColor in this prop just add border to the wrapper of these dots, not to every separate circle.

**Comment by Haskkor** [comment]
Hi,

I've added the `stylePinCodeCircle` property in the latest version :).

Cheers,
Jeremy
