### ISSUE TITLE
Invalid PIN handling is not consistent

### ISSUE THREAD

**Issue by DesmanLead** [fnzc/react-native-pincode#82]
Invalid PIN handling on PIN confirmation screen and on PIN entering screen is not consistent.
PIN confirmation screen: error state is flushed after a timeout.
PIN entering screen: error state is flushed only on any number button tap.

It's probably better to flush error state after a timeout in both cases.

**Comment by Haskkor** [comment]
Hi,

Thanks for that! I've changed it in the latest version :).

Cheers,
Jeremy
