### ISSUE TITLE
it is possible use the passcode from IOS ?

### ISSUE THREAD

**Issue by ncornejo** [fnzc/react-native-pincode#83]
Hello, Thanks for the great component. 
I saw that React Native Touch ID has the option of use the passcode of IOS when Touch/Face ID is not disponible (passcodeFallback - iOS - by default set to false. If set to true, will allow use of keypad passcode.) . It is posible use this feature with react-native-pincode ? 
regards!

**Comment by Haskkor** [comment]
Hi!

Thanks for that. Fully makes sense I don't know why I turned it off :).
It's fixed.

Cheers,
Jeremy

**Comment by ncornejo** [comment]
Great! but is possible listen the cancel event of the passcode ?  actually when I press Cancel I get the Pincode Screen and I think it is better if I can , for example, go back.

Thanks !

**Comment by Haskkor** [comment]
It can be nice indeed. I won't take the time to do this soon though. You're welcome to make a PR if you want or I'll do it eventually :)
