### ISSUE TITLE
Increase width of number grid

### ISSUE THREAD

**Issue by alberthitanaya** [fnzc/react-native-pincode#84]
Would it be possible to make something like this using the props currently provided?:

![image](https://user-images.githubusercontent.com/13726496/57212200-4a5a2280-7026-11e9-9370-0b659a41ea1c.png)

I can see that grid imposes a maxwidth on the number pads, would it be possible to expose that or some other control so we can control the width of the number pad?

Thanks

**Comment by Haskkor** [comment]
Hi,

I've managed to do this with minor changes, I'll try to publish it soon :).

Cheers,
Jeremy

**Comment by Haskkor** [comment]
Hi,

With the latest version, you can now use the full width.
I've done something real quick that looks like that:

![Screen Shot 2019-05-23 at 2 39 49 PM](https://user-images.githubusercontent.com/10620919/58221969-a338f300-7d68-11e9-81ef-2701e263b02f.png)

So you should be able to reach your goal!

```
class PinCode extends React.PureComponent<IProps, IState> {

  render() {
    return (
      <PINCode
        status={'choose'}
        stylePinCodeButtonCircle={styles.buttonCircle}
        stylePinCodeEmptyColumn={styles.colEmpty}
        stylePinCodeColumnButtons={styles.colButtonCircle}
      />
    )
  }
}

export default PinCode

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  colButtonCircle: {
    marginLeft: grid.unit / 2,
    marginRight: grid.unit / 2,
    alignItems: 'center',
    width: grid.unit * 8,
    height: grid.unit * 4
  },
  colEmpty: {
    marginLeft: grid.unit / 2,
    marginRight: grid.unit / 2,
    width: grid.unit * 8,
    height: grid.unit * 4
  },
  buttonCircle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: grid.unit * 8,
    height: grid.unit * 4,
    backgroundColor: 'rgb(242, 245, 251)',
    borderRadius: grid.unit * 4
  }
})
```

Cheers,
Jeremy
